### ISSUE TITLE
Allow Admins to delete documents

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#363]
**We need to ensure anything deleted here is a *Soft Delete* **

This will entail deleting:

* The document content
* Any document comments
* Any document annotations
  * Any annotation permissions, tags, ranges
  * Any annotation sub-comments
  * Any note_metas associated with the annotation ( likes, dislikes, flags )
* Any document metas ( support / oppose )
* Document sponsors, dates, statuses, categories

We will then want an interface that lets admins browse deleted documents and re-create them.  This interface will simply list any documents that have been soft deleted.  We potentially will want an option to hard delete them.

**Comment by cmbirk** [comment]
This is going to be handled by the editor.

**Comment by krues8dr** [comment]
Reviewing this now, I think only the actual document needs to be (soft) deleted, all of the relational items will be hidden as a result and inaccessible.  Though the API needs to be updated to enforce this logic.

I don't think it's necessary to email commenting users when a parent document is removed - I can't think of a single other service that does this - only the document owner(s) needs to be notified imho.

Instead of soft delete, I think the same document status we've discussed elsewhere ( #725 ) makes more sense and will be easier to query.  The only question in my mind is do we allow users to un-delete documents?  If so, we'll need two statuses - `deleted (by user)` and `deleted (by admin)` where the latter cannot be reversed by a user.  I'd suggest *not* letting users undelete their documents - though this is very un-Wordpress-like, it's a lot less work to manage.

**Comment by sethetter** [comment]
To clarify:

* Documents can be deleted by admins (reversible)
* Documents can be deleted by users (reversible?)
* Doing #725 first may be necessary
* Filter viewable docs in certain contexts by status

@cmbirk @krues8dr

**Comment by krues8dr** [comment]
I would do #725 first, to make this more sane.

**Comment by sethetter** [comment]
@krues8dr right. I'll tackle that then come back to this.

**Comment by cmbirk** [comment]
The comments / annotations will need to be soft deleted as well.  On the user pages we have an activity stream that these would not be hidden from otherwise.

**Comment by cmbirk** [comment]
I do agree that we'll want to track the `deleted_by` part

**Comment by sethetter** [comment]
@cmbirk @krues8dr Do we want to allow any person in a group to be capable of deleting a document that belongs to the group? Just want to clarify because it seems like that could potentially be an issue.

Also, should user deletion be reversible like admin deletion will be?

**Comment by krues8dr** [comment]
My vote is yes and yes.  We're assuming groups are offices that are sharing responsibilities, so if an owner leaves, the rest of the staff will need to be able to remove it.  And if someone accidentally removes a document, they should be able to undelete it.  Though we might not want to have a "recycle bin" or anything right now from a UX perspective yet.

**Comment by sethetter** [comment]
I'll want to talk through the UX for displaying `deleted` documents on the user and admin side for the purpose of undeleting. Do we include it in their document list under a "Deleted" header? Have a separate screen for viewing deleted docs? I'm leaning more towards the latter.

**Comment by cmbirk** [comment]
My vote is yes and yes as well.

**Comment by cmbirk** [comment]
I think having a separate screen for viewing deleting docs makes more sense.

**Comment by sethetter** [comment]
:+1:
