### ISSUE TITLE
Missing data for redesign assets

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#522]
Here are the pieces of data I'm missing for the redesign; they might exist and I just haven't found them after a cursory glance.

* Feature bill
* Recent Activity Bill list 
* Most Active Bill list
* Stats for all bills (Comments, Views, last updated, shares?)

**Comment by cmbirk** [comment]
I'm going to add these routes:

* `/api/docs/featured`
* `/api/docs/recent`
* `/api/docs/active`

And then I'm going to add the comment count and annotation count to the `/api/docs` endpoint.  We don't have shares build in since we removed AddThis a little while ago.  Where are we using the views stats?

**Comment by cmbirk** [comment]
I'll also add the total number of participants.

**Comment by cmbirk** [comment]
I've also added annotation_comments_count.  We really need to clean up the Annotation model, but I've opened a separate ticket for discussion on that in the 2.0 milestone: #526

**Comment by cmbirk** [comment]
@billhunt you should have everything you need in the /api/docs/ endpoint after 4d761c0 .  Still working on the other 3 endpoints.

**Comment by cmbirk** [comment]
The recent addition was `user_count` for each document, fyi

**Comment by cmbirk** [comment]
@krues8dr `/api/docs/recent/<number?>` endpoint will default to 10, but `/api/docs/recent/1` will give you the most recently updated document.  I pushed a fix for that route in 0e26973

**Comment by cmbirk** [comment]
`/api/docs/active/<number?>` endpoint is set up the same way.  Each document has an extra `participationTotal` attribute which is the sum of Annotations, Comments, and AnnotationComments.

This is added in 41d7b4e

**Comment by cmbirk** [comment]
I've opened up a separate issue for the actual Featured Document functionality in #527

**Comment by cmbirk** [comment]
@krues8dr what is the image size for the featured document image?

**Comment by krues8dr** [comment]
633 x 352 or so.

**Comment by cmbirk** [comment]
@krues8dr I've finished the `api/docs/featured` route.  Documents now include the `thumbnail` attribute which is a relative link to the document image, and a featured document must have an image.  It defaults to the most recently created document and a default image if there is no featured document.

I haven't created any image manipulation yet.  We should probably set something up like Facebook uses for changing your profile where it has an opaque selection with a set dimensions so that we can ensure they fit into the designs.  I'll open a separate ticket for that in the Future milestone for now.
