### ISSUE TITLE
Annotation drawer missing close link

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#570]
![screen shot 2015-06-22 at 11 18 45 am](https://cloud.githubusercontent.com/assets/764851/8285265/46dff780-18d0-11e5-915e-3f0dc6f6dd23.png)

**Comment by cmbirk** [comment]
@boboroshi @krues8dr what are your thoughts on using a small left panel for closing instead of a link at the top?  Something like the attached that would change shade on hover.  I like the idea because as your attention goes from the conversation back to the document you have the close function in line with that path.


![slider close](https://cloud.githubusercontent.com/assets/764851/8285559/1ee78a3e-18d2-11e5-98f0-dc7fd54b14d5.png)

**Comment by boboroshi** [comment]
We can go with something like this. First, we should use an actual arrow icon instead of the > character. Second, it should highlight blue when being hovered over. Might be worth having "CLOSE PANEL" running vertical (text rotated 90° from baseline) under the arrow. The whole bar should be the link, and we might want to kick it up to 30px (it looks 20 right now) just for and easier target on tablets/touch

**Comment by cmbirk** [comment]
@krues8dr take a look at the `annotation-pane-close` branch.  I've added this and it works, but want to make sure it's in line with the semantic setup you've put in place.

**Comment by cmbirk** [comment]
@boboroshi here's what we have in that branch:
![screen shot 2015-06-24 at 3 11 33 pm](https://cloud.githubusercontent.com/assets/764851/8339117/39fb4506-1a83-11e5-9f6e-4b8bce56afa1.png)

**Comment by krues8dr** [comment]
The close link is at the top of this panel, and I've attached that panel to stay at the top, so this shouldn't be so much of an issue for now.

**Comment by krues8dr** [comment]
This works as-is, I'm punting on redesigning this view.
