### ISSUE TITLE
Discussion Tab Unclear for Adding General Comment to Document

### ISSUE THREAD

**Issue by seamuskraft** [opengovfoundation/madison#577]
Not clear that "General Document" comments are happening under "Discussion" tab.

**Comment by cmbirk** [comment]
We should change that to 'Comments' or something like that.

**Comment by seamuskraft** [comment]
Agreed.  We should also be pulling all the page's discussion (annotations,
comments, comments on comments, etc.) into the renamed "Comments" page,
methinks.

- Seamus

Seamus Kraft
Executive Director & Co-Founder
The OpenGov Foundation <http://OpenGovFoundation.org>
Ph: +1-760-659-0631
Tweet Us @FoundOpenGov <http://twitter.com/foundopengov>

**Comment by cmbirk** [comment]
The annotations will stay with the main document body, because they aren't useful out of context.  The comments tab has always been just a reddit-style comment stream for people who don't want to jump into the text of the document.  It's hidden because it's *almost always* a much less useful conversation.
