### ISSUE TITLE
Permalinks open discussion tab

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#630]
Permalinks to annotations end up with the discussion tab open, which obviously doesn't scroll to the intended annotation on the document tab.

**Comment by barryvdh** [comment]
I'm also having this issue. it links to `/docs/example-document#annotation_6`, but when clicked, nothing changes.
When I paste the url to visit the link, I end up on the discussion page, not the sidebar.

I would rather that, when I click on a annotation, it would just jump to the sidebar (instead of the popup at all), any idea how that would be best handled?

**Comment by cmbirk** [comment]
I think this is in `documentPageController.js`.

**Comment by sethetter** [comment]
Permalinks should now be working for annotations, annotation comments, doc comments and doc sub comments.

It will highlight the relevant linked item and scroll to it. If it's an annotation, the side panel will also open up.
