### ISSUE TITLE
Don't require users to verify emails on registration

### ISSUE THREAD

**Issue by cmbirk** [opengovfoundation/madison#635]

**Comment by cmbirk** [comment]
I'm on board with this.

We have the prompt that is shown if you register via Twitter that sits at the top and consistently asks for an email.  We can use the same thing if the user hasn't verified their email address.

We'll want to make sure that emails aren't being sent to any unverified addresses, however.

**Comment by waldoj** [comment]
I feel like there's a design pattern for this, because I've definitely used sites that require an email registration, but that let me use the site in the interim. Maybe it's that they require confirmation, but there's a grace period of X minutes or hours until the account has to be confirmed?

The one catch with that is if there are any actions that the user can perform on Madison that will send an email to their account—you don't want somebody to be able to create an account using somebody else's email address and then trigger a harassing series of emails to them. And it's surely a PITA to have to check whether the user is confirmed before they can perform that email-sending action (so much simpler to just not provide access at _all_ without a confirmed address).

**Comment by krues8dr** [comment]
:+1: Yup, we talked through all this.

* [ ] Show message when user logs in telling them to confirm
* [ ] Don't send any emails if the user hasn't confirmed
* [ ] Cron job to nag users if they haven't confirmed after X days

**Comment by doshitan** [comment]
#954 does everything listed here except setup a cron job to nag the user with an email if they still haven't verified their email address. Instead it simply displays a banner at the top of every page asking them to verify until they do so, which I think is sufficient.
