### ISSUE TITLE
A group creation form doesn't validate fields

### ISSUE THREAD

**Issue by Vanuan** [opengovfoundation/madison#639]
If you don't fill all required fields on the page `groups/edit`, it fails silently.

**Comment by Vanuan** [comment]
Thanks. I see validations, but they are permanent (don't autohide)

**Comment by krues8dr** [comment]
Right, we disabled autohiding since people weren't always seeing the messages, per #629.  If you re-submit the form they'll be dismissed, or you can close each individually.  We could be smarter about this and auto-validate as you go, but that'll have to come later since we don't have any validation-only API endpoints setup.

**Comment by Vanuan** [comment]
No, they are not dismissed on resubmission. Ok, so it's a global thing, not specific to groups.
