### ISSUE TITLE
Popup when not authorized

### ISSUE THREAD

**Issue by barryvdh** [opengovfoundation/madison#665]
Is it possible to restrict some pages with the roles, but when not logged in, show a login popup, before showing the page? This would be easier for link sharing etc (eg private documents), as the user can be redirected to the intended page.

**Comment by krues8dr** [comment]
This would be possible - but right now the concept of "private documents" is designed to allow anyone with the link to view the document, without needing to login.  To do this *right* we'd need a better concept of fine-grained permissions like what Google Docs does:

* Anyone can view this document
* Anyone with the link can view this document
* Anyone with the link and who is a registered user can view this document
* Only these users can view this document: (list here)

**Comment by barryvdh** [comment]
How do I use the standard redirect?

In my case, I want to make all documents private, so I add the role permission to the document route:

```
.state( 'doc-page', {
        url: "/docs/:slug",
        controller: "DocumentPageController",
        templateUrl: "/templates/pages/doc.html",
        data: {
          title: "Document Page",
          authorizedRoles: [ USER_ROLES.admin, USER_ROLES.independent, USER_ROLES.groupMember, USER_ROLES.basic ]
        }
      } )
```

But that gives a flash message bout not being logged in, an redirects to the homepage. Instead, I would have preferred a redirect to loginpage, and when loggin in, back to intended document. Is that already possible then?

**Comment by krues8dr** [comment]
Ah, that looks like a bug and the offending line is here:  https://github.com/opengovfoundation/madison/blob/master/public/js/app.js#L96

It'll be a couple of hours before I can get to this, sorry for the delay.  Feel free to hotfix and send over a PR if you have the time and interest though!  Thanks!

**Comment by krues8dr** [comment]
This one actually turns out to be more insidious than it originally appeared.  Even after changing that line, the login page is *not* redirecting to the last referenced url.  I still haven't quite figured out why after poking at this for an hour, so this might carryover into tomorrow.  Sorry for the extended delay!

**Comment by cmbirk** [comment]
Yeah, it looks like there isn't an easy way to grab the previous state:

https://github.com/angular-ui/ui-router/issues/92

Shouldn't be too tough to recreate though.  I can take a stab at it this evening.

**Comment by krues8dr** [comment]
I've got the previous state, I just copied what I did on the editor.  The weird part is that `$location.url` isn't actually redirecting.  Very strange.

**Comment by krues8dr** [comment]
You can see where I'm at here - I'm trying to see if missing a local reference to user is the problem.

**Comment by cmbirk** [comment]
So you don't need to re-grab the user, because `AuthService.login()` handles that by calling `AuthService.getUser()`.  

It's currently trying to redirect to `/index` instead of the index state.  We're also only setting the previous state if there is an authorization error.  I would assume we want to return the user to the previous page on **any** login.

**Comment by cmbirk** [comment]
I got the login redirect finished for any states that don't require parameters in 22f51b5.  Not sure why the correct parameters aren't passing.

**Comment by krues8dr** [comment]
@cmbirk that doesn't actually seem to be redirecting for me.  The `previousState` object doesn't have what I'd expect in it:  `{name: "", url: "^", views: null, abstract: true}`.  It also looks like you're saving that data on *every* state change, which I think isn't what you'd want.  You can see the way I originally was handling it here:  https://github.com/opengovfoundation/madison/blob/22f51b52a4032f073498825bcb0c0984b07ecae5/public/js/app.js#L107-L114  I'll keep poking at this for a bit.

**Comment by krues8dr** [comment]
Hmm, yeah, state doesn't ever actually reach the requested page because of the auth intercept, so you can't actually get the correct state that way.  I think this is why I ended up using location instead on the editor.  I'm going to keep pursuing that route here as I'd originally started on.

**Comment by cmbirk** [comment]
I was definitely getting the state to come through on the `SessionService.`  I can take a look at this in a bit, the only thing I didn't have working was state routes with parameters.

There are going to be other places down the road where we will want to grab the previous state, so I'm ok with storing that on state change.  It shouldn't affect much at all.

**Comment by krues8dr** [comment]
There's a race condition in here that's causing this - the user isn't being set in the AuthService before the new page is requested for the edit user page, and as a result you get kicked back to the login screen even though you're technically logged in.  That's why I was doing the call to /current manually.  

I'm still having the same issue with `state` and I'm not sure how to work around it, since that state is never technically being set in the first place.  (`console.log`ging the page shows it's never hit.)  Using `location` works perfectly.

Anyway, I've got a working fix here.  I'm happy to look at other options, but as I said those were not working for me at all.

**Comment by cmbirk** [comment]
Always happy with working fixes :)

**Comment by krues8dr** [comment]
Great.  If we're all :+1: here I'll merge this into dev.

**Comment by cmbirk** [comment]
Cool, cool.  We may need to figure out a way to broadcast that current user event and subscribe to it instead of making manual calls, but we can cross that bridge later.

**Comment by krues8dr** [comment]
Ok, this is merged into the `dev` branch - @barryvdh could you give that a shot and see if that works for you?

**Comment by krues8dr** [comment]
Hmm.  I guess one thing here is that `authorizedRoles` auth list is only on the front-end, and more importantly only works for filtering what roles can view a page.  You'll need to actually change the API to deny users access to private documents if they're not logged in.

**Comment by cmbirk** [comment]
Yeah, that shouldn't be too tough.  Just handle in the `error()` method when grabbing the document from the API.

**Comment by sethetter** [comment]
No more angular, closing!
