### ISSUE TITLE
Sponsor name is missing

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#712]
On the main site, we've got a lot of empty "Sponsored by" items.  This could be due to the i18n work (not replacing the proper string), or it could be that we just don't have data here (in which case we should hide the Sponsor).

**Comment by cmbirk** [comment]
I'm seeing this on the homepage.  It looks like `doc-list-item.html` doesn't check the sponsor exists before including the i18n label

**Comment by krues8dr** [comment]
Should all documents have a sponsor?

**Comment by cmbirk** [comment]
Yeah, they should.  We didn't originally require it, so these may be older documents that need a sponsor set.

Currently it sets the logged in user as the sponsor so this doesn't happen.  

When admins were drafting documents for other users we didn't set the admin as the sponsor though and it was their responsibility to set one.

**Comment by sethetter** [comment]
I'm running into this for getting sponsors listed on the deleted documents page for #363. I'm going to tackle it in this issue by adding `display_name` to the User model on the API side [as a virtual property](https://stackoverflow.com/questions/17232714/add-a-custom-attribute-to-a-laravel-eloquent-model-on-load).

**Comment by sethetter** [comment]
Looks like it's already there, not sure why it isn't coming through. I'll keep digging.

**Comment by sethetter** [comment]
[Finally tracked down the culprit](https://github.com/opengovfoundation/madison/blob/00bdddd489c4a33cea6329582ae78dc5e094c8cf/app/Models/Doc.php#L129-L138).

That applies to the entire query. So the if statement always fails if at least one document in the DB is group sponsored. So it joins the group table instead of the user table. No clue how to get it to apply to individual records yet. But this is a bigger task than I expected so I’ll wait until I’m done with this issue to take care of it.
