### ISSUE TITLE
Homepage alignment off (some parts flush left)

### ISSUE THREAD

**Issue by krues8dr** [opengovfoundation/madison#784]
Per #776.  This is also a good opportunity to review some of the sizes and breakup of this page - we might want to hide the entire Active Legislation pane, for instance - it's far less useful than the browse/search on the right.  

A bonus feature would be a way in the API to optionally exclude the featured document from the feed of Recent Legislation so there isn't a duplicate right off the bat.

**Comment by sethetter** [comment]
I think hiding the "Active Legislation" pane makes sense. There is probably a good way to include the pane in an alternate view (behind a tab or something). But for now could just be hidden.

**Comment by emanuelfeld** [comment]
@sethetter I'm still seeing this when on the homepage (though not on a legislation page).

![image](https://cloud.githubusercontent.com/assets/4269640/12328864/6330ec0a-baab-11e5-93ad-204b8d57468a.png)
![img_0341](https://cloud.githubusercontent.com/assets/4269640/12328869/694a04dc-baab-11e5-8569-68e1a43daf46.PNG)

**Comment by sethetter** [comment]
@emanuelfeld bummer! I'll take a look at that shortly. Might be time to pull out the XCode emulators ;)

**Comment by krues8dr** [comment]
The second one is on my plate over at #798 - that X is frustrating me like whoa.

**Comment by sethetter** [comment]
@krues8dr glad to hear it, it's been bothering me too :)

**Comment by sethetter** [comment]
Turns out that legislation "B20-0825" has the word "Accountability" in it, which is stretching the page out a bit, haha. Might need to lower the font size a tad on smaller screen sizes.

**Comment by krues8dr** [comment]
I did just drop the font size once, fwiw, in a commit yesterday.

**Comment by sethetter** [comment]
@krues8dr larger words are going to push the width of the page quite a bit. In this case it was the word "Accountability", which is long, but I'm sure some longer ones could show up in legislation titles.

I dropped the size of `h1, h2, .large-header` a bit, as well as the font-size of the doc titles in the doc-list on homepage.

Looking at the doc list though, I wonder if it might be best to move to a single column design for the individual doc list items, with stats below the title instead of the to the right of them.

Thoughts?

**Comment by krues8dr** [comment]
@sethetter yeah, single column is preferable, I mentioned that over on #808.  `make it so` :point_right: :)

**Comment by sethetter** [comment]
Cool, I'll call this one done and then do the single column work in #808.
