### ISSUE TITLE
Annotation side-link sometimes becomes misaligned with relevant section

### ISSUE THREAD

**Issue by emanuelfeld** [opengovfoundation/madison#822]
Have not been able to consistently reproduce (often seems to fix itself with a page refresh).. 

Browser Chrome Version 47.0.2526.111
OS El Capitan

**Comment by krues8dr** [comment]
So, the annotation numbers on the side are loaded in right after the content and annotations are finished, which only occurs after the rest of the page is done loading.  These are positioned at that time to the top of the content blocks the annotations reference (and _not_ the annotations themselves, due to potential overlaps).  It's altogether possible that resizing the browser or some late lingering asset rendering could cause that content to reshuffle and make these lose their place (though there are no images on the page to cause a restructuring like that).  

However, that's a relatively rare occurrence - you'd really have to squish the window to change the text flow.  Meanwhile, watching for the resize event is pretty expensive - considering how much else we've got going on on the page, personally I'm not super enthusiastic about that. Especially since on busy pages this could involve moving a thousand DOM objects around.

Another way to do this would be to set a timer and see if just the first one had moved, but again you'd have to reshuffle the whole page while a user was on it, which would definitely look like a bug - things would just suddenly fly around to new locations.

Considering the rarity of this bug, I'm inclined to leave this as a known issue for now.  If someone finds a different race condition happening that could be effecting this, I'd certainly reconsider my position.  

cc: @cmbirk @sethetter for feedback.

**Comment by emanuelfeld** [comment]
Considered using tables? :stuck_out_tongue:

Related to this, if the window width is in something like [768px,990px], the annotation info jumps left over the text.

![image](https://cloud.githubusercontent.com/assets/4269640/12373580/b8ea65bc-bc4b-11e5-925c-c07e8debe9ff.png)

**Comment by krues8dr** [comment]
Yeah, that would happen - 768px is the small screen breakpoint which triggers the mobile layout.

**Comment by sethetter** [comment]
This should be good in v4
