### ISSUE TITLE
Move to group only sponsorship model

### ISSUE THREAD

**Issue by sethetter** [opengovfoundation/madison#888]
Currently we have what is essentially a polymorphic relationship for document sponsors (either users or groups). Moving to something that would be a bit cleaner and also open up an easier permission model in the future would be to have each user by default have a group that they belong to and are the only user in.

@krues8dr want to elaborate?

**Comment by krues8dr** [comment]
Sure.  

1) The original conversation here was around moving all of the logic around sponsors to the `document` model as a polymorphic has_many relationship.  That way we don't have to dig through that logic as much.

2) Most SQL flavors (MySQL & PostgreSQL at least) don't allow a polymorphic foreign key, you always have to have a single table.  We can live without this relationship being enforced, but at the expense of performance.  Since Eloquent (Laravel's ORM) mostly hides this logic from us, it's not a huge deal - but things will be much slower.

3) An easy solution to 2. is create a group for each user that's an Independent Sponsor, and that user is the owner of the group.  This means that sponsors will *always* be groups from a data standpoint moving forward.  This simplifies the logic in a lot of places.

**Comment by sethetter** [comment]
Need to create a couple migrations:

* [ ] Add an `individual` flag to the `groups` table
* [ ] Move all existing independent sponsors to `groups` table with the `individual` flag set

On the second, we'll leave the independent sponsor data intact for a bit, in case we need a failsafe to revert back to.

**Submitting verification request**

Next will be to tackle the independent sponsor request screens. Filling out the request and submitting it should hit an API endpoint in the `Group` controller. I'm thinking it should go through the same group creation endpoint, but with a flag passed to signify it's an individual group.

**Verifying requests**

As for verifying sponsorships, it would be ideal to consolidate this into a single screen. So some language would need to change from "Group Verification" to "Sponsor Verification", where a sponsor could be a group or an individual. The existing group verification screen could be used, and we will designate on the screen which verification requests are for groups and which are for individuals.

**My documents screen**

The separate sections for "individually sponsored" and "group sponsored" could go away. Instead we would just list them by group, and the first group would be the individually sponsored ones.

**Group management**

We would probably want to omit the listing of the individual group from the Group Management page. To update the info on the individual group (address, etc), should probably be handled from the account management screen.

**Data modeling**

This should be much more simplified with this approach. Instead of having the `sponsors()` method on the `Doc` model that pulls in both `userSponsors` and `groupSponsors`, it will just refer to groups. We'll be able to strip out the logic everywhere that is handling the data differences between groups and individual sponsors and make sure they all just have the necessary attributes as a group.

---

I'm sure I've missed something here, but this is enough to get me started. This is going to be a big one.  Wish me luck :)

**Comment by sethetter** [comment]
When an individual submits a sponsorship request, the address and other information are stored in the users table, which makes sense. However, for an individual group to be created it also has to be stored in the groups table.

Do we duplicate the data? Or just move to keeping this data in the groups table?

I vote for the latter. @krues8dr what say you?

**Comment by krues8dr** [comment]
I think we duplicate.  We also allow users to be `verified` and we need that information then as well - so it needs to be attached to the user.

**Comment by sethetter** [comment]
@krues8dr +1
