### ISSUE TITLE
How login with admin user?

### ISSUE THREAD

**Issue by johnfelipe** [opengovfoundation/madison#955]

**Comment by krues8dr** [comment]
If you've run `php artisan db:seed`, you'll have a few default accounts, and a default admin Role.  Those are defined in [config/madison.php](https://github.com/opengovfoundation/madison/blob/master/config/madison.php).  Otherwise, you'll need to manually create the admin.  Right this moment, the command line tools to do this are broken, so in the meantime, you can do it the old fashioned way:

1. Create an admin role in the database with this query: `INSERT INTO roles SET name='Admin';`
1. Create a user account through the usual signup process.  Confirm your account via the email that is sent.
1. Find you're user's account id in the `users` table, as well as the Admin group's id in the `roles` table.  If this is a new install, both will probably be `1`.
1. Link your admin user to the admin role with this query, filling in your ids from the previous step: `INSERT INTO role_user sSET user_id = 1, role_id = 1;`

**Comment by johnfelipe** [comment]
you can verify that
http://jhonfelipeurregomejia.com:2016/

        'admin_email' => 'admin@example.com',
        'admin_password' => 'password',

I cant login

**Comment by krues8dr** [comment]
At first glance it doesn't look like cookies are getting set.  Check the COOKIE_DOMAIN in your .env file, and check that your nginx config is writing cookies to a valid location.

**Comment by johnfelipe** [comment]
Sorry for my dummie knowledge, pls send me link with instructions for nginx and COOKIE_DOMAIN, tnks

**Comment by krues8dr** [comment]
COOKIE_DOMAIN in your case should probably be 'jhonfelipeurregomejia.com'.  If you're running PHP with FastCGI then it's actually in php.ini not nginx, it should be `session.save_path` I think.  You'll need to make sure that directory is writable by nginx.

**Comment by johnfelipe** [comment]
cd madison
	mkdir session
	sudo nano /etc/php5/fpm/php.ini
	session.save_path = "/home/felipe/madison/session"

may be that?

**Comment by krues8dr** [comment]
Sure, just make sure that's readable & writable by the nginx process.

**Comment by krues8dr** [comment]
Do you need further help with this?
